/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesGUI;

import estruturas_lineares.non_ordered.DoubleLinkedUnorderedList;
import files.GestaoFicheiroComentarios;
import files.GestaoFicheiroMensagens;
import java.io.File;
import java.io.IOException;

import javax.swing.table.DefaultTableModel;
import models.Comentario;
import models.Mensagem;
import models.Utilizador;

/**
 *
 * @author Fábio Rêgo
 */
public class Comentarios extends javax.swing.JFrame {
    
    private final DefaultTableModel modelTable = new DefaultTableModel();
    private Utilizador utilizador;
    private Comentario comentario;
    private Mensagem comentarioM;
    private GestaoFicheiroMensagens gestMensagem = null;
    private GestaoFicheiroComentarios gestComentarios = null;
    private DoubleLinkedUnorderedList<Mensagem> mensagensCom = new DoubleLinkedUnorderedList<>();
    private DoubleLinkedUnorderedList<Comentario> comentarios = new DoubleLinkedUnorderedList<>();

    /**
     * Creates new form Comentarios
     */
    public Comentarios() throws IOException {
        
        this.gestMensagem = new GestaoFicheiroMensagens();
        this.gestComentarios = new GestaoFicheiroComentarios();
        initComponents();
        initiFrames();
        
    }
    
    public Comentarios(Comentario comTemp) throws IOException {
        
        this.comentario = comTemp;
        this.gestMensagem = new GestaoFicheiroMensagens();
        this.gestComentarios = new GestaoFicheiroComentarios();
        initComponents();
        initiFrames();
        
    }
    
    private void testeRetornoComentarios() {
        File check = new File("comentarios.txt");
        
        if (check.exists()) {
            //mensagensCom = gestComentarios.lerFicheiroComentario();
            comentarios = gestComentarios.lerFicheiroComentario();
            //mensagensCom.addToRear(comentarioM);
            System.out.println("Tamanho da Lista[Comentarios]Classe:Comentarios_: " + mensagensCom.getCountElements());
        }
    }

    /**
     * Metodo responsavel por adicionar uma coluna ao modelo
     */
    private void personalizeColumsRows() {
        
        tableOfComments.setModel(modelTable);
        
        modelTable.addColumn("Comentario");
        modelTable.addColumn("Utilizador");
        
        tableOfComments.setRowHeight(150);
        
    }
    
    private void initiFrames() throws IOException {
        
        testeRetornoComentarios();
        personalizeColumsRows();
        
        this.button_toApagar.setEnabled(false);
        if (comentarios.isEmpty()) {
            
            modelTable.addRow(new Object[]{"Sem comentários", 0});
            
        } else {
            
            for (Comentario com : comentarios) { //percorre a lista de comentarios existentes na plataforma e popula a lista, posteriormente e necessario verificar se os utilizadores sao amigos do utilizador online 
              // for (Mensagem mensCom : mensagensCom) {
//                if(mensCom.getClass().equals(com.getDescricao())){
                      modelTable.addRow(new Object[]{com.getDescricao(), com.getUtilizadorSender().getNome()});
                }
//                else {
//                    modelTable.addRow(new Object[]{"Sem comentários para mostrar..."});
//                }
//            }
//        }
     //       }
        
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableOfComments = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        button_toApagar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BLOG SOCIAL :: COMENTÁRIOS");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tableOfComments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(tableOfComments);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Comentários");

        button_toApagar.setText("Apagar Comentário ");

        jButton1.setText("Sair ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(button_toApagar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_toApagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(15, 15, 15))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_toApagar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableOfComments;
    // End of variables declaration//GEN-END:variables
}
