/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesGUI;

import estruturas_lineares.non_ordered.DoubleLinkedUnorderedList;
import files.GestaoFicheiroComentarios;
import files.GestaoFicheiroMensagens;
import files.GestaoFicheiroUtilizadores;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Comentario;
import models.Mensagem;
import models.Utilizador;

/**
 *
 * @author ZeLuis
 */
public class profile_frame extends javax.swing.JFrame {

    private final DefaultTableModel modelTable = new DefaultTableModel();
    private Utilizador utilizador;
    private Mensagem userMensagem;
    private GestaoFicheiroMensagens gestMensagem = null;
    private GestaoFicheiroComentarios gestComentarios = null;
    private DoubleLinkedUnorderedList<Mensagem> mensagens = new DoubleLinkedUnorderedList<>();
    private DoubleLinkedUnorderedList<Comentario> comentarios = new DoubleLinkedUnorderedList<>();

    /**
     * Creates new form profile_frame
     *
     * @throws java.io.IOException
     */
    public profile_frame() throws IOException {

        this.gestMensagem = new GestaoFicheiroMensagens();
        this.gestComentarios = new GestaoFicheiroComentarios();
        initComponents();
        initiFrames();

    }

    profile_frame(Utilizador userTemp) throws IOException {

        this.utilizador = userTemp;
        this.gestMensagem = new GestaoFicheiroMensagens();
        this.gestComentarios = new GestaoFicheiroComentarios();
        initComponents();
        initiFrames();

    }

    /**
     * Metodo responsavel por adicionar uma coluna ao modelo
     */
    private void personalizeColumsRows() {

        tableofNews.setModel(modelTable);

        modelTable.addColumn("Publicacoes");
        modelTable.addColumn("Privacidade");

        tableofNews.setRowHeight(150);

    }

    private void testeRetornoMensagens() {
        File check = new File("mensagens.txt");

        if (check.exists()) {
            mensagens = gestMensagem.lerFicheiroMensagem();
            mensagens.addToFront(userMensagem);
            System.out.println("Tamanho da Lista: " + mensagens.getCountElements());
        }
    }

    private void testeRetornoComentarios() {
        File check = new File("comentarios.txt");

        if (check.exists()) {
            comentarios = gestComentarios.lerFicheiroComentario();
            System.out.println("Tamanho da Lista: " + comentarios.getCountElements());
        }
    }

    private void initiFrames() throws IOException {

        this.usernameProfile.setText(utilizador.getNome());

        testeRetornoMensagens(); //retorna as mensagens existentes em ficheiro - provavelmente tera que usar algum metodo da network.
        testeRetornoComentarios();
        personalizeColumsRows(); //metodo responsavel por personalizar as colunas do tabela com o nome 

        if (mensagens.isEmpty()) {

            modelTable.addRow(new Object[]{"Sem publicações para mostrar..."
                + "Sem comentários", 0});

        } else {

            for (Mensagem mes : mensagens) {
                if (mes.getUser().getNome().equals(utilizador.getNome())) {//percorre a lista de mensagens existentes na plataforma e popula a lista, posteriormente e necessario verificar se os utilizadores sao amigos do utilizador online 
                    if (mes.isPriv()) {
                        modelTable.addRow(new Object[]{mes.getConteudo(), "Privada"});
                    } else {
                        modelTable.addRow(new Object[]{mes.getConteudo(), "Pública"});
                    }

                } else {
                    modelTable.addRow(new Object[]{"Sem publicações para mostrar..."
                        + "Sem comentários", 0});

                }

            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelto_InfoUser = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameProfile = new javax.swing.JLabel();
        numbermessagesProfile = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableofNews = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        comentarioProfile = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BLOG SOCIAL :: PERFIL DO UTILIZADOR");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        panelto_InfoUser.setBackground(java.awt.Color.white);

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setText("Utilizador:");

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("Nº de mensagens:");

        usernameProfile.setText("[Nome_Utilizador]");

        numbermessagesProfile.setText("jLabel4");

        javax.swing.GroupLayout panelto_InfoUserLayout = new javax.swing.GroupLayout(panelto_InfoUser);
        panelto_InfoUser.setLayout(panelto_InfoUserLayout);
        panelto_InfoUserLayout.setHorizontalGroup(
            panelto_InfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelto_InfoUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelto_InfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelto_InfoUserLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernameProfile))
                    .addGroup(panelto_InfoUserLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numbermessagesProfile)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        panelto_InfoUserLayout.setVerticalGroup(
            panelto_InfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelto_InfoUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelto_InfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernameProfile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelto_InfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numbermessagesProfile))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        tableofNews.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Publicacoes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableofNews);

        jButton1.setText("Sair ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        comentarioProfile.setColumns(20);
        comentarioProfile.setRows(5);
        jScrollPane1.setViewportView(comentarioProfile);

        jButton2.setText("Comentar ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelto_InfoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelto_InfoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String comment = this.comentarioProfile.getText();
        Comentario newComentario = new Comentario(comment, utilizador);

        if (comment != null) {

            gestComentarios.escreverFicheiroComentario(newComentario);
            this.comentarioProfile.setText("");

        } else {
            JOptionPane.showMessageDialog(this, "O Comentario encontra-se vazia", "Try Again!", JOptionPane.WARNING_MESSAGE);
            this.comentarioProfile.setText("");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea comentarioProfile;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel numbermessagesProfile;
    private javax.swing.JPanel panelto_InfoUser;
    private javax.swing.JTable tableofNews;
    private javax.swing.JLabel usernameProfile;
    // End of variables declaration//GEN-END:variables
}
